# Sequence: .zshenv -> .zprofile -> .zshrc -> .zlogin -> .zlogout

# Execute code that does not affect the current session in the background.
# Sorin Ionescu <sorin.ionescu@gmail.com>
{
 	# Compile the completion dump to increase startup speed.
 	zcompdump="${ZDOTDIR:-$HOME}/.zcompdump"
 	if [[ -s "$zcompdump" && \
		(! -s "${zcompdump}.zwc" || \
		"$zcompdump" -nt "${zcompdump}.zwc") ]]; then
		zcompile "$zcompdump"
	fi
} &!
