# Sequence: .zshenv -> .zprofile -> .zshrc -> .zlogin -> .zlogout

if [[ -s "${ZDOTDIR:-$HOME}/.biome/prezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.biome/prezto/init.zsh"
fi

# Prompt
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Customizations (config-home)
[[ -f ~/.zprojrc ]] && source ~/.zprojrc
